# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
